== eBook-speaker

Read eBooks with Linux using a speech-synthesizer +
(C)2019 J. Lemmens

=== Description
eBook-speaker reads an eBook and uses a speech synthisizer for output. +
eBook-speaker reads the EPUB format. If the given file is not an
EPUB it will be converted using several tools like calibre, lowriter,
pandoc, pdftotext, scanimage, pnmflip, unrtf or tesseract.
(http://en.wikipedia.org/wiki/Comparison_of_e-book_formats) +
eBook-speaker can use any TTS (Text-To_speech) tool, as long as the TTS
can read the text from a file and writes the audio to a .wav file. +
The file ~/.eBook-speaker.xml contains TTS tools to use.

=== Requirements
Be sure the following extra packages exist on your system:

   libncursesw5
   libmagic1
   libpulse0
   libxml2
   libsox2
   libsox-fmt-mp3
   libsox-fmt-pulse
   unar
   txt2man
   man2html-base
   html2text
   gettext
   espeak
   libreoffice-writer
   calibre
   pandoc
   poppler-utils
   ghostscript
   tesseract-ocr
   sane-utils
   netpbm
   unrtf
   wget

The following packages are needed to make the manual and the html document:

   txt2man
   man2html

=== Usage
As a mortal user, give on the command line,:

   $ ebook-speaker

A file-manager will appear from which an input-file can be selected.
An input-file can also be given as argument to eBook-speaker:

   $ ebook-speaker file.epub

This starts reading the eBook and printing the content on
the screen. After giving an [ENTER], the eBook will be read using the
espeak speech synthisizer. One can select another TTS using the 't'command.

A list of items on the eBook will appear. Press <ENTER>
to start playing. When reading of an item has finished, eBook-speaker will
play the next item and the cursor will automatically skip
to that item, so that your braille-terminal will display the name
of that item.

For keyboard navigation, plese press 'h' or '?'.

eBook-speaker is multilingual. The following languages are currently
supported: +
bulgarian, dutch, english, finnish, french, german, portuguese,
Serbian, spanish.

Enjoy

Jos Lemmens

==== Note
From his brother Kees on November 9, 2021 : I am very sorry to inform you that Jos quietly passed away this morning.
He will be remembered as our own dear, clever, little "Stephen Hawking".

On behalf of users of eBook-speaker and Daisy-player, current mainteners would also thank him for his tremendous work. Jos, we miss you.
